name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: bulid-kobayashi-cpu
      run: make
      working-directory: apps/kobayashi-cpu
    - name: build-physical-cpu
      run: make
      working-directory: apps/physical-cpu
#    - name: build-kobayashi-gpu
#      working-directory: kobayashi/gpu
#      run: |
#          mkdir build
#          cd build
#          cmake ..
#          cmake --build .

